alias: studio lights
description: ""
trigger:
  - device_id: c5a38392ef848c63ccd675977add2601
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
    id: switch.single
  - device_id: c5a38392ef848c63ccd675977add2601
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
    id: switch.double
condition: []
action:
  - if:
      - condition: device
        type: is_off
        device_id: 2b59955d4d3d4017810bb378b0398e6f
        entity_id: light.studio
        domain: light
    then:
      - service: script.generic_lights
        data:
          light_entities:
            - light.studio
    else:
      - if:
          - condition: trigger
            id: switch.double
        then:
          - service: script.generic_lights_off
            data:
              light_entities:
                - light.studio
        else: []
mode: single
