alias: switch.lights
description: ""
trigger:
  - device_id: 267bb1ad388ba3ff5b5d8b5ffd933c4f
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
condition: []
action:
  - if:
      - condition: device
        type: is_off
        device_id: 2af9d77159fa1723b981f4f602854376
        entity_id: light.livingroom_lights
        domain: light
    then:
      - service: script.turn_on
        data:
          entity_id: script.1695965166392
    else:
      - service: script.turn_on
        data:
          entity_id: script.night_mode
mode: single
